### ISSUE TITLE
Escape hatch for unknown keys

### ISSUE THREAD

**Issue by p0nce** [dlang-community/configy#46]
Ideas:
- hardcode `_` prefix being ignored

OR 

- unknown keys call a (nullable) callback delegate, a bit like the missingFunction callback in old Derelict loader library. The return value of the callback indicate to either ignore or fail
- duplicate keys call a (nullable) callback delegate, that choose either to error or ignore (keep only one of the two)

**Comment by Geod24** [comment]
Unknown keys can just be ignored with `StrictMode.Ignore`.
